README.md, dev-tools/setup.sh
* Delete root created file structure in uploads
* Only run EP commands if they are avaiable to avoid annoying error
messages
=> Minor fixes to setup.sh for dev-tools

dev-tools/Dockerfile, dev-tools/dev-env-plugin.php, dev-tools/setup.sh, dev-tools/wp-config-defaults.php
This is the first step to supporting https out of the box on dev-env
=> Setup https

nginx/default.conf
Read https://github.com/Automattic/vip/pull/869 for context
=> Extra config for Nginx

dev-tools/scripts/user-container-setup.sh
The `php-fpm` container actually needs the `www-data` group too.
This change makes sure group exists before creating user and creates it otherwise.
=> create www-group if doesnt exists group

skeleton/Dockerfile
* Use `ghcr.io/automattic/vip-container-images/alpine:3.14.3`;
* Remove unnecessary `cd`;
* Use `--no-cache` with `apk del`.
=> Update Skeleton image

wordpress/Dockerfile, wordpress/add-version.sh
* use `ghcr.io/automattic/vip-container-images/alpine:3.14.3`;
* fix `shellcheck` issues
=> Update WordPress image

dev-tools/Dockerfile, dev-tools/add-site.sh, dev-tools/scripts/user-container-setup.sh, dev-tools/setup.sh
* Use `ghcr.io/automattic/vip-container-images/alpine:3.14.3`;
* Fix `shellcheck` warnings (mainly [this](https://github.com/koalaman/shellcheck/wiki/SC2181), [this](https://github.com/koalaman/shellcheck/wiki/SC2002), [this](https://github.com/koalaman/shellcheck/wiki/SC2086), and [this](https://github.com/koalaman/shellcheck/wiki/SC3020))
=> Update dev-tools image

.github/CODEOWNERS
=>  CODEOWNERS file to get the auto review request on team

.github/workflows/wordpress.yml, wordpress/versions.json
Supports adding extra tags to the WordPress image so we can signal to the automation script (and docker users) that the image is locked (will not be removed by automation).
=> Workflow code to add extra tags to Docker image

wordpress/versions.json
* Changes Pre-Release to 5.9.2-alpha-52803 (fcf2500f49341dfce84c3ac68d963a6a92874f64)
* Change 5.9 to 5.9 -> 5.9.1
=> Update dev-env WordPress Images

wordpress/versions.json
=> flipped tag/ref

wordpress/versions.json
Removed 5.9.2 pre-release and change 5.9  to 5.9.2
=> Update dev-env to latest.

wordpress/versions.json
=> Add WP 6.0-RC2

.github/workflows/php-fpm.yml, php-fpm/Dockerfile
Update the base image to `php:7.4-fpm-alpine3.15`.
=> Bump Alpine to 3.15 for php 7.4 image

dev-tools/setup.sh
This beautiful issue with non-mounted volumes came back.
This change makes the thinks fail more noticeably. As the Timeout message got kinda drawned among other things.
I am happy to change the error line to something else.
```
Waiting for service vip-search ...
Waiting for service database ...
Waiting for service vip-search ...
Scanning to determine which services are ready... Please standby...
Waiting for core files to be copied
ERROR: WP core files not found. Please try to restart or destroy the environment
ERROR ==> ERROR: WP core files not found. Please try to restart or destroy the environment 
NAME               vip-local                                                                                 
LOCATION           /home/pavel/.local/share/vip/dev-environment/vip-local …
```
=> Volumes fun

wordpress/versions.json
Lets give the people what they want!
=> Changed the RC to the official 6.0 release tag

wp-core-test-runner/Dockerfile
Update `nvm` from 0.39.0 to 0.39.1.
=> Update nvm to 0.39.1

php-fpm-alt/Dockerfile.81
* Downgrade alpine from edge to 3.16.0
=> Update base image for php-fpm-alt:8.1

wordpress/versions.json
Adds WordPress 6.0.1 to container images.
=> added 6.0.1 to available container images

.github/workflows/update-wp-versions.yml
#287 is the example of what this workflow does.
=> Automatically update versions.json when a new WP version gets released

php-fpm/rootfs74/etc/php7/conf.d/xdebug.ini.template, php-fpm/rootfs80/etc/php8/conf.d/xdebug.ini.template, php-fpm/rootfs81/etc/php81/conf.d/xdebug.ini.template
Witht he new logfile we can more closelly see if and why not is xdebug working.
=> Add xdebug log to debug xdebug

.github/workflows/alpine.yml, .github/workflows/dev-tools.yml, .github/workflows/mariadb-lite.yml, .github/workflows/mu-plugins.yml, .github/workflows/nginx.yml, .github/workflows/php-fpm.yml, .github/workflows/skeleton.yml, .github/workflows/statsd.yml, .github/workflows/traefik.yml, .github/workflows/wordpress.yml, .github/workflows/wp-core-test-runner.yml, .github/workflows/wp-test-base.yml, .github/workflows/wp-test-runner.yml
This PR will help reduce the load on GHA runners and decrease the build queue size.
=> Automatically cancel stale workflows

php-fpm/Dockerfile.74, php-fpm/Dockerfile.80, php-fpm/Dockerfile.81, php-fpm/Dockerfile.82
Add `memcached` extension to PHP images to test the new Memcached-based object cache.
=> feat(php): Add php-pecl-memcached

wordpress/extra/db-config.php, wordpress/extra/wp-content/db.php
This PR adds HyperDB (automattic/hyperdb@e6d92c304fbc7cfa6c3ca8c3fcd96a12b81abe52) and a sample configuration file to make the dev environment resemble the production environment.
=> feat(wordpress): Add HyperDB

wordpress/extra/wp-content/db.php
Sync HyperDB with Automattic/HyperDB@703f5f0834015e3a05459930635cf0d5c0ad3e55
=> chore(deps): Update HyperDB

.github/actions/build-docker-image/action.yml, .github/workflows/mu-plugins.yml, mu-plugins/Dockerfile
See: #394
This is an alternative implementation.
=> feat(mu-plugins): Add support for production build

dev-tools/setup.sh
This PR moves the code to wait for ES to come online higher, so that it runs before we check whether WP is installed.
The logic now is:
1. Wait for WP Core to be copied
2. Check for, or generate, wp-config.php
3. Wait for MySQL to come online
4. Provision WP database if necessary
5. Copy dev-env-plugin.php
6. If the env has ES, wait for ES to come online
7. Check whether WP is installed, install if it is not; maybe set up ES indices.
The (1), (3), and (6) checks are duplicated in VIP CLI. By moving (6) higher, we can remove these checks from VIP CLI.
=> refactor(dev-tools): Check for ES regardless whether WP is installed

nginx/default.conf
Ref: https://github.com/Automattic/vip-go-mu-plugins/pull/3989
=> feat(nginx): Add Prometheus endpoint

dev-tools/dev-env-plugin.php, dev-tools/wp-config-defaults.php
Like #419, but we do that earlier.
=> fix(dev-tools): Fix Host header for Codespaces

dev-tools/wp-config-defaults.php
For https://github.com/Automattic/vip-go-mu-plugins/pull/4111#issuecomment-1426102313
=> Dev-tools: Move VIP_GO_APP_ENVIRONMENT & VIP_GO_ENV constants up

php-fpm/Dockerfile.74, php-fpm/Dockerfile.80, php-fpm/Dockerfile.81, php-fpm/Dockerfile.82
This PR adds Ghostscript to our PHP images to match the production environment.
Closes: #386
=> feat(php-fpm): Add ghostscript

README.md
Additionally, expand on version management.
=> Update README to add more instructions on how to use the built images locally

wordpress/extra/wp-content/object-cache-next.php, wordpress/extra/wp-content/object-cache-stable.php
To match what is in https://github.com/Automattic/vip-go-mu-plugins/tree/develop/drop-ins/object-cache now that we're loading from there
=> Update object-cache-*.php files to match mu-plugins

dev-tools/Dockerfile, skeleton/Dockerfile, wordpress/Dockerfile
For some reason, Dependabot fails (again):
```
updater | 2023/03/22 13:32:58 ERROR <job_631171708> Error processing automattic/vip-container-images/alpine (RuntimeError)
updater | 2023/03/22 13:32:58 ERROR <job_631171708> Expected content to change!
updater | 2023/03/22 13:32:58 ERROR <job_631171708> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:66:in `updated_dockerfile_content'
updater | 2023/03/22 13:32:58 ERROR <job_631171708> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:33:in `block in updated_dependency_files'
updater | 2023/03/22 13:32:58 ERROR <job_631171708> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:22:in `each'
updater | 2023/03/22 13:32:58 ERROR <job_631171708> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:22:i …
```
=> chore(deps): Update ghcr.io/automattic/vip-container-images/alpine to 3.17.2

php-fpm/Dockerfile.80, php-fpm/Dockerfile.81, php-fpm/Dockerfile.82, php-fpm/rootfs82/etc/php82/conf.d/memcache.ini
Ref: https://github.com/Automattic/vip-codespaces/pull/32
=> fix(php-fpm): Add missing PHP extensions

.github/workflows/dev-tools.yml, dev-tools/setup.sh, dev-tools/wp-config-multisite.php.tpl
To play nice with https://github.com/Automattic/vip-cli/pull/1334
=> Dev-tools: Configure for subdirectory usage

php-fpm/Dockerfile.80, php-fpm/Dockerfile.81, php-fpm/Dockerfile.82
This fixes https://github.com/Automattic/vip-cli/issues/1339
=> fix(php-fpm): Downgrade mariadb-client to stay compatible with MySQL

README.md, dev-tools/setup.sh
We currently don't retry on failed ES check, which beats the purpose of the while loop.
=> Retry Elasticsearch cluster healthcheck

.github/dependabot.yml, .github/workflows/photon.yml, nginx/default.conf, photon/Dockerfile, photon/rootfs/etc/photon/config.php, photon/rootfs/etc/php81/conf.d/gmagick.ini, photon/rootfs/etc/php81/php-fpm.d/docker.conf, photon/rootfs/etc/php81/php-fpm.d/zz-docker.conf
This PR adds an image for Photon service.
=> feat: Add Photon image

php-fpm/rootfs-php/mods-available/mailhog.ini, php-fpm/rootfs-php/mods-available/mailpit.ini
=> fix(php-fpm): Fix quotes in sendmail_path

dev-tools/dev-env-plugin.php
Reverts Automattic/vip-container-images#513
=> Revert "Guard against double inclusion of dev-env-plugin"

php-fpm/Dockerfile.74, php-fpm/Dockerfile.80, php-fpm/Dockerfile.81, php-fpm/Dockerfile.82
This PR‌ adds `vim` and `nano` into our PHP images.
=> feat(php-fpm): add vim and nano

nginx/default.conf
This PR pulls the changes from the VIP nginx config.
=> fix(nginx): synchronize nginx config with VIP

.github/actions/build-docker-image/action.yml, .github/actions/build-docker-image/markdown.tpl, .github/actions/trivy/action.yml, .github/workflows/alpine.yml, .github/workflows/build-skeleton.yml, .github/workflows/dev-tools.yml, .github/workflows/mu-plugins.yml, .github/workflows/nginx.yml, .github/workflows/photon.yml, .github/workflows/php-fpm.yml, .github/workflows/skeleton.yml, .github/workflows/traefik.yml, .github/workflows/wordpress.yml
Take advantage of GitHub Advanced Security and upload SARIF reports generated by Trivy.
[This is what it looks like](https://github.com/Automattic/vip-container-images/security/code-scanning?query=pr%3A575+is%3Aopen)
=> ci: generate SARIF reports

photon/Dockerfile, php-fpm/Dockerfile.74, php-fpm/Dockerfile.80, php-fpm/Dockerfile.81, php-fpm/Dockerfile.82, php-fpm/Dockerfile.83
=> security: fix all fixable CVEs

nginx/Dockerfile, nginx/default.conf, nginx/errors/50x.html
This PR adds a detailed error page for 50x errors with troubleshooting steps. 
This should help customers to debug the errors.
=> Add error interceptor custom error page for 50x responses

php-fpm/Dockerfile.83
This PR:
* updates the base Ubuntu image to 24.04 (LTS) for PHP 8.3;
* improves the build time for the image by using the prebuilt dependencies.
=> chore(deps): update ubuntu image to 24.04 for php-fpm

dev-tools/setup.sh, php-fpm/rootfs/usr/local/bin/run.sh
=> fix(dev-env): enable Xdebug for all SAPIs

traefik/Dockerfile
Reverts Automattic/vip-container-images#728
=> Revert "chore(deps): Bump traefik from 2.11.2 to 3.0.0 in /traefik"

dev-tools/add-site.sh, dev-tools/dev-env-plugin.php, dev-tools/setup.sh
This should harden against unwanted code interactions. 
Additionally this updates wording to be more descriptive and bumps the timeout to 120 for mu-plugins copy.
Sister PR of https://github.com/Automattic/vip-cli/pull/1879
=> Update dev-tools scripts

php-fpm/rootfs-php/cli/php.ini, php-fpm/rootfs-php/fpm/php.ini, php-fpm/rootfs-php/mods-available/mailhog.ini, php-fpm/rootfs/usr/local/bin/run.sh
✅ Automattic/vip-cli#1813 needs to be released first
=> refactor!(php-fpm): drop support for MailHog

.github/workflows/php-fpm.yml, php-fpm/Dockerfile.84
This PR adds an image for PHP 8.4.
=> feat: add PHP 8.4

.github/workflows/traefik.yml
=> ci: fix a typo

.github/actions/build-docker-image/action.yml
* #988 
* #990 
* #994 
* #997
=> ci: update actions

dev-tools/Dockerfile, mu-plugins/Dockerfile, skeleton/Dockerfile, wordpress/Dockerfile
Update Alpine from 3.20.3 to 3.21.0.
=> chore: update images to Alpine 3.21

wordpress/dev-tools/dev-env-plugin.php, wordpress/dev-tools/wp-config-defaults.php
This PR adds support for integrations.
Related: Automattic/vip-go-mu-plugins#6101, Automattic/vip-cli#2199, Automattic/vip-cli#2198
=> feat(wordpress): add support for integrations

.github/actions/build-docker-image/action.yml
=> chore(ci): update `aquasec/trivy` to 0.59.1

wordpress/Dockerfile
Install WordPress tests Library along with WordPress.
=> feat(wordpress): add WordPress Tests Library

wordpress/Dockerfile
This PR backports performance optimizations from #1086.
=> refactor(wordpress): use build platform arch to build WPTL

.github/actions/build-docker-image/action.yml, .github/workflows/codeql.yml, .github/workflows/stale.yml, .github/workflows/wp-test-runner.yml
This PR sets up a CodeQL analysis for GitHub actions and fixes the issues discovered.
Refs:
* https://github.blog/security/application-security/how-to-secure-your-github-actions-workflows-with-codeql/
* https://github.blog/changelog/2024-12-17-find-and-fix-actions-workflows-vulnerabilities-with-codeql-public-preview/
=> ci: set up CodeQL workflow

php-fpm/Dockerfile.81, php-fpm/Dockerfile.82, php-fpm/Dockerfile.83, php-fpm/Dockerfile.84
Ref: https://github.com/mydumper/mydumper/releases/tag/v0.18.1-1
=> chore(deps): update `mydumper` to 0.18.1-1

php-fpm/Dockerfile.81, php-fpm/Dockerfile.82, php-fpm/Dockerfile.83, php-fpm/Dockerfile.84
=> refactor(php-fpm): use `php-helpers` image to improve build time

.github/actions/build-docker-image/action.yml, .github/workflows/php-helpers.yml, .github/workflows/wp-test-runner.yml
* Bump `docker/login-action` from 3.3.0 to 3.4.0 (#1119, #1123)
* Bump `docker/setup-docker-action` from 4.2.0 to 4.3.0  (#1120, #1124)
=> chore(deps): bump Docker-related actions
