Automattic/vip-container-images

php-fpm/Dockerfile, php-fpm/run-php-fpm.sh, php-fpm/run.sh
This "disables" xdebug unles env variable `XDEBUG=enable`.
I am not sure if removing xdebug.ini is the best way, but it gets away with the warning at least.
Follow-up in vip: https://github.com/Automattic/vip/pull/838
This can go out first. It will disable the xdebug on all the new environments without a nice way of enabling it. That is ok I think? Because we want xdebug disabled by default.
=> Disable xdebug

dev-tools/wp-config-defaults.php
Otherwise 2fa is enforced. Which is not neeed for local dev-env
=> Set  'WPCOM_IS_VIP_ENV' to false

.github/workflows/dev-tools.yml, dev-tools/wp-config-defaults.php
Moving the latest version of the `wp-config-defaults.php` file from `vip dev-env` to the Docker image.
This PR also bumps de dev-tools version to 0.6.
=> Updating dev-tools config defaults and bumping version to 0.6

.github/workflows/dev-tools.yml, .github/workflows/mu-plugins.yml, .github/workflows/nginx.yml, .github/workflows/php-fpm.yml, .github/workflows/skeleton.yml, .github/workflows/statsd.yml, .github/workflows/wordpress.yml, wordpress/add-version.sh
This PR adds dry runs to all images. That is, whenever we open a PR, we will try to build the images on a GitHub Action but we will no push them. This way, we can tell whether the image is properly set up.
=> Adding Dry Runs on all workflows

dev-tools/setup.sh, dev-tools/wp-config-defaults.php
This PR sets `VIP_DISABLE_STATSD` flag conditioned to an environment variable. We are making this change to accommodate the fact that we don't always enable statsd on the dev environment.
=> Disable statsd conditionally

php-fpm/Dockerfile
Some development tools - such as [wc-smooth-generator](https://github.com/woocommerce/wc-smooth-generator) - relies on GD Graphics Library to be available to generate product images, as such it's useful to be available on the development environment. 
This PR includes this library on the `php-fpm` image.
I have tested this with `dev-env` locally, and it works as expected.
=> Add GD Graphics Library to php-fpm image

nginx/default.conf
In prod we redirect anything under `/wp-content/uploads` to the file service - so not to `php` code. Let's do something similar on dev-env.
=> Change nginx image path to wp-content

.github/workflows/dev-tools.yml, dev-tools/setup.sh
To copy the dev-env plugin we need root permissions (because mu-plugins are mapped and they are owned by root).
With the latest change of the template we are changing the setup to **not** run as root and do the copy in a seperate task.
More info in here - https://github.com/Automattic/vip/pull/888
=> Dont copy dev-env-plugin as part of setup

.github/dependabot.yml
This PR instructs Dependabot to monitor GitHub Actions and create PRs if they become outdated.
=> Dependabot: monitor GitHub actions

.github/dependabot.yml, .github/workflows/wp-test-runner.yml, wp-test-runner/Dockerfile, wp-test-runner/install-wp.sh, wp-test-runner/runner.sh
This PR adds a new image to run CI tests for WordPress using CircleCI as the provider.
The image features:
* latest WP versions since WP 5.5 + trunk (updated daily)
* PHP 7.4, 8.0, 8.1
* PHPUnit 7, 8, 9 (latest versions)
* NodeJS 14, npm 6
* Subversion
The image is used in a test branch of [vip-go-mu-plugins](Automattic/vip-go-mu-plugins#2544). Its main advantages are that it reduces the CI time by providing all dependencies baked into the image and that it reduces the load on WP.org SVN (which sometimes rate-limits us).
Even though it is used by `vip-go-mu-plugins`, it can be used with any WP plugin (I use it myself for my plugins).
=> Add WP Test Runner image

dev-tools/scripts/user-container-setup.sh
We don't strictly need `www-data` group to have host user's group ID. 
Trying to set the GID to some group that already exists break the execution. I tried to attempted to add the group with that specific ID and then without similar to what lando does, but there were some issues with `groupadd` not releasing file lock soon enough for the second run.
I also added a line that `chown`s the `www-data` home back after the id switch.
=> Ignore group ID

wp-test-runner/runner.sh
This PR adds support for PHP options to the test runner. This is useful for local development.
One of the use cases is to profile a slow test. You will need to pass some options to PHP, like `-d xdebug.mode=profile -d xdebug.output_dir=/home/circleci/project/tmp`. This PR allows to do that via `PHP_OPTIONS` environment variable.
=> Add support for PHP options

php-fpm/run.sh
* Switch `run.sh` to `sh` from `bash` — `sh` is built into `busybox` in Alpine, and consumes much less resources than `bash`;
* Add `exec` to `php-fpm` to replace the current shell with `php-fpm` and save a bit of RAM.
=> Update php-fpm image

wp-test-runner/Dockerfile
This PR fixes two issues at once (I know it's not the best practice, but these changes are tied together and working on them in
multiple branches will lead to merge conflicts):
1. The "grave" issue: "Compilation failed: unrecognised compile-time option bit(s) at offset 0".  This one seems to be caused by an [outdated PCRE library](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1830385.html); the library has to be updated from the PPA the PHP is installed from.
2. Build failures resulting from transient network conditions (like "Unable to connect to archive.ubuntu.com")
3. Speed up the build process by using [eatmydata](https://manpages.debian.org/testing/eatmydata/eatmydata.1.en.html)
=> Fix issues with the PCRE library and speedup build

wp-test-runner/runner.sh
Disable or enable XDebug with `phpdismod`/`phpenmod` explicitly to make sure it does not affect tests.
Now, if XDebug is disabled, it won't even be loaded.
Related to Automattic/vip-go-mu-plugins#2630
=> Explicitly disable or enable XDebug

dev-tools/wp-config-defaults.php
This change adds parity to our production environment with regards to loading the vip-pre-config file
This has already been added to svn and will need to be available also in dev-env.
=> Add vip-pre-config to dev-env loadout

.github/dependabot.yml, .github/workflows/mariadb-lite.yml, mariadb-lite/Dockerfile
This image is a combination of `eatmydata` and the classic MariaDB image. It is good to be used for unit tests because it is faster than the traditional image. However, it is **not safe** to be used in production because it does not care about the data — any crash can damage the database beyond any repair. It is OK for tests, because the database lives in a throwaway container.
I am going to write a P2 explaining how this works.
=> Add MariaDB-Lite image

wp-test-runner/Dockerfile, wp-test-runner/configure-environment.sh, wp-test-runner/create-database.sh, wp-test-runner/install-wp.sh, wp-test-runner/runner.sh
* Move environment initialization code into `configure-environment` (this makes it easier to debug failed tests directly in the container);
* Add missing PHP 8.1 packages;
* Make test runner less verbose;
* Do not require `phpunit.xml` or `phpunit.xml.dist`;
* Add support for a pre-test script (will be run prior to PHPUnit in case some additional configuration is required).
=> Update WP Test Runner

.github/dependabot.yml, .github/workflows/wp-core-test-runner.yml, wp-core-test-runner/Dockerfile, wp-core-test-runner/configure-environment.sh, wp-core-test-runner/create-database.sh, wp-core-test-runner/install-wp-core.sh, wp-core-test-runner/runner.sh
This image is similar to WP Test Runner. Its purpose is to run WP Core tests.
Currently, in CI, we spent the most time building the WP Core. This image has the core pre-built.
**How to test locally**
Set up the database container:
```bash
docker network create wptest
docker run -d --rm --network wptest --name mysql \
-e MYSQL_ROOT_PASSWORD=wordpress \
-e MARIADB_INITDB_SKIP_TZINFO=1 \
-e MYSQL_USER=wordpress \
-e MYSQL_PASSWORD=wordpress \
-e MYSQL_DATABASE=wordpress_test \
--tmpfs /var/lib/mysql \
ghcr.io/automattic/vip-container-images/mariadb-lite:10.3
```
Run this from `vip-go-mu-plugins` directory (adjust the image name as necessary):
```bash
docker run -it --rm --network wptest \
-e MYSQL_HOST=mysql \
-e WP_MULTISITE=1 \
-v …
```
=> Add WP Core Test Runner image

wp-core-test-runner/Dockerfile, wp-core-test-runner/install-wp-core.sh
* Bake WP Importer into the image
* Reduce image size by removing directories not used during tests (node_modules, src, .svn)
=> Update WP Core Test Runner

dev-tools/setup.sh
So that we have the mu-plugin when installing wordpress to avoid the error with 2FA
=> moves up mu-plugin setup

dev-tools/dev-env-plugin.php
On multisite, we need to do a more complex setup for the admin user.
This is too difficult to do when interacting with wp cli during sql import. So instead we build our custom command that will abstract away all the complexity and only be triggered from the sql import command.
Replacing this try block -  https://github.com/Automattic/vip/blob/5372034e86d3aba96358286d6eef01a5c879432f/src/bin/vip-dev-env-import-sql.js#L66
As an added benefit we will be able to not show Error if the user already exists.
=> Add custom admin creation command

wordpress/update-version.sh
wordpress/update-version.sh will not stage changes when the subtree was already at the right commit ref
=> update-version.sh exit when commit ref is the same

nginx/default.conf
Add support for multisites running in [subdirectories mode](https://wordpress.org/support/article/create-a-network/#step-0-before-you-begin). 
With this change, now these two alternatives will work:
- http://subsite1.local.vipdev.lndo.site/
- http://local.vipdev.lndo.site/subsite1/
This PR was tested by adding the modification to the file extra.conf.
=> Added nginx conf support for multisites running in subdirectories mode

wordpress/versions.json
"Locked" will support one-off images that don't get removed.
"Prerelease" will signal to the user that the image is not stable.
=> WordPress Images new properties: "locked" and "prerelease"

wordpress/add-version.sh, wordpress/del-version.sh, wordpress/versions.json
* Changes to wordpress/versions.json to update the dev-environment images and metadata
* On wordpress/add-version.sh I swapped the argument order so that the "tag" argument is the first argument
* Fixed an error with the assignment of locked and prerelease arguments
* Changed wordpress/add-version.sh so that it tries to match by tag instead of ref.
* The reason why I make this change is because I want to make an image of 5.7 that has a ref of 5.7.5, an image that already exists
* I want to make each line distinct by tag instead of ref
* Changed wordpress/del-version.sh so that it deletes by tag instead of ref, to be consistent with the changes in wordpress/add-version.sh
=> Update the dev-environment WordPress images, metadata and scripts

wp-test-runner/configure-environment.sh, wp-test-runner/runner.sh
* Fall back to PHPUnit 7 if `vendor/bin/phpunit` does not exist or is not executable;
* Use the bundled copy of Yoast PHPUnit Polyfills if the app under test does not have its own copy;
* Deduplicate code
=> Bug fixes for WP Test Runner

wordpress/versions.json
Added locked WordPress versions 5.8.1 and 5.8.2 to the WordPress manifest.
* Retaining these should support users who have previously checked out these images into an environment.
=> Bugfix - Missing WordPress Images post culling

nginx/default.conf
Some local dev-env sites are 502ing whenever a POST request is sent from wp-admin. This is due to an error stating:
` 502 bad gateway
2022/01/20 02:47:05 [error] 102#102: *128 upstream sent too big header while reading response header from upstream, client: 172.20.0.2, server: localhost, request: “GET /wp-admin/edit.php?s=&post_status=all&post_type=post&_wpnonce=0bd12f11ce&_wp_http_referer=%2Fwp-admin%2Fedit.php&m=0&cat=0&capi_content_type=0&liveblog_state=&filter_action=Filter&paged=1 HTTP/1.1”, upstream: “fastcgi://172.21.0.8:9000”, host: “newsdna.vipdev.lndo.site”`
Have replicated locally and it seems their sites are sending a large header request. Updating these values within `etc/nginx/conf.d/default.conf` fixes this issue.
=> Change fastcgi values to a higher value

.github/workflows/php-fpm.yml, php-fpm/Dockerfile
This PR adds the following extensions:
- apcu
- bcmath
- calendar
- exif
- gmagick
- gmp
- intl
- mcrypt
- pcntl
- shmop
- soap
- sockets
- ssh2
- sysvsem
- sysvshm
- timezonedb
- zip
Enables:
- Zend OPcache
What's missing:
- newrelic (it requires a license key)
=> CANTINA-844: synchronize PHP extensions with the production environment

php-fpm/Dockerfile
From the [documentation](https://hub.docker.com/_/php),
> Unlike PHP core extensions, PECL extensions should be installed in series to fail properly if something went wrong. Otherwise errors are just skipped by PECL. For example, pecl install memcached-3.1.4 && pecl install redis-5.1.1 instead of pecl install memcached-3.1.4 redis-5.1.1. However, docker-php-ext-enable memcached redis is fine to be all in one command.
=> Separate 'pecl install' steps and clean up PEAR cache

nginx/default.conf
When using WP for multisite in subdirectory mode, the urls would not be routed correctly.
For example. `http://multisite.vipdev.lndo.site/test/wp-admin` would end in an infinite redirect.
These rules that mimic closely our prod settings should suppress that. As they rewrite the file lookup on server from <subsite>/(wp-admin|wp-includes|wp-content|...) to exclude the subsite bit.
=> [nginx] Update rewrite rules

.github/workflows/php-fpm.yml, .github/workflows/wordpress.yml
For builds where we use caching,
* pull base images before build: this is to ensure that we have the freshest of the base image (e.g., with the latest security patches applied);
* scope cache to "subproject": to ensure that cache for one build (e.g., wordpress) does not overwrite the cache for another build (say, php-fpm). Although nothing critical happens in case when one cache overwrites another, docker will be unable to use the cache which defeats the whole purpose of caching
=> Pull base images and properly scope cache

dev-tools/setup.sh
There was a bug that manifested in the following error on the initial start/installation. Weirdly, it works on the restart, so I decided to `ls -al`  during the script and found out that some folders inside `/wp` have root as the owner. 
```
Warning: require(/wp/wp-includes/pomo/mo.php): failed to open stream: No such file or directory in /wp/wp-settings.php on line 116 [$ /usr/local/bin/wp option get siteurl] [wp-settings.php:116 require(''), phar:///usr/local/binvendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1317 require('wp-settings.php'), phar:///usr/local/binvendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1235 WP_CLI\Runner-&gt;load_wordpress(), phar:///usr/local/binvendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:28 WP_CLI\Runner-&gt;start(), …
```
=> Explicitly chown /wp during dev-tools/setup.sh to avoid permission errors

dev-tools/dev-env-plugin.php
In specific cases we get an infinite https -> https redirect. Here is one scenario to reproduce:
* dev-env create --slug test
* go to wp-admin
* Settings -> Readign
* Go to https version of homepage - https://test.vipdev.lndo.site/ -> infinite redirect
* vim /home/pavel/.local/share/vip/dev-environment/test/.lando.yml
* Change devtools from image to local build:
```
build:
context: /home/pavel/git/automattic/vip-container-images
dockerfile: /home/pavel/git/automattic/vip-container-images/dev-tools/Dockerfile
```
*  dev-env destroy --soft --slug test (because docker volumes are fun!)
* repeat the first steps again
* Should work fine now.
The fix here suppresses redirects that are only due to http -> https which makes life easier on local dev-env.
=> Supress https redirects

dev-tools/setup.sh
add --silent tag to chown operation so as to not cause panic if the chown cannot be performed
prevents someone from seeing the unsightly eyesore in this image:
=> chown with "--silent" in setup.sh

wordpress/versions.json
* Removed images for 5.8.3, 5.8.2, 5.8.1 (They were there for legacy reasons but they need to be moved beyond at this point)
* Changed the 5.9 ref to 5.9.3 as is the new release as of yesterday.
=> dev-env update WordPress image selection

wordpress/versions.json
This PR adds WordPress 6.0-beta1 to the list.
The diff makes it a bit hard to read so it's easier just to view the file.
=> Add 6.0-beta1

wordpress/versions.json
Follow up to #186, it seems `6.0-beta1` doesn't work as a tag.
=> Rename the tag to 6.0

wordpress/versions.json
There's going to be a follow-up PR with the fix for VIP-CLI
=> Remove 6.0 as there's a bug in VIP-CLI preventing the user from actually using it

wp-core-test-runner/runner.sh, wp-test-runner/runner.sh
This PR adds to variables to test runners:
* `RUN_TESTS`: when not empty, run an interactive shell instead of running tests. This allows for running tests with custom parameters or modifying scripts locally;
* `DEBUG_TESTS`: when not empty and the test script exited with a non-zero code, run an interactive shell for debugging.
=> Add debug mode to debug failed tests

README.md, wordpress/add-version.sh
Update wordpress/add-version.sh to be more explicit about the parameters, fix eq comparisons resulting in the incorrect values for cacheable, locked and prerelease, sort the list of versions in reverse chronological order (newest first)
=> Update WordPress add-version.sh script 

wp-core-test-runner/runner.sh, wp-test-runner/runner.sh
Fix a bug introduced in #190.
An empty value for `RUN_TESTS` caused the runner to run tests, not skip them. This made `RUN_TESTS=1` counterintuitive, as this would cause the runner not to run the tests.
This PR renames `RUN_TESTS` to `SKIP_TESTS` to match what the variable actually controls.
=> Rename RUN_TESTS to SKIP_TESTS to match what it actually does

php-fpm-alt/Dockerfile.80, php-fpm-alt/Dockerfile.81
8.0 and 8.1 images miss /usr/bin/php; this prevents WP CLI form running. As a result, `vip dev-env start` is unable to install WordPress automatically.
=> Create a symlink to /usr/bin/php

dev-tools/setup.sh
It remains to be seen whether `/wp/wp-includes/pomo/mo.php` is a good thing to check or if there's something else we should check.
This also removed the `chown` as it doesn't seem to be helpful in the situation.
There's going to be a counter-part on the CLI side to get rid of the PHP healthcheck as it's also not helpful
=> Implement a simple check that runs until the files are copied to make sure setup only proceeds after, otherwise we're risking race conditions

wordpress/versions.json
This PR adds `trunk` which just points to HEAD of the GitHub repo, and 6.0-RC1 which points to https://github.com/WordPress/WordPress/commit/638a31b8d3000eb7d0c13b84ec6c7f5740cffe4f
=> WordPress: add 6.0-RC1 and trunk.

php-fpm/Dockerfile
See z-148012
Steps to test:
1. Build the image
2. Run the newly built image:
```sh
docker run -it --rm ghcr.io/automattic/vip-container-images/php-fpm:7.4 php -i | grep -F 'JPEG Support'
```
3. `JPEG Support => enabled` should appear
The expected `libgd`-related output from `php -i`:
```
gd
GD Support => enabled
GD Version => bundled (2.1.0 compatible)
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.10.4
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 8
PNG Support => enabled
libPNG Version => 1.6.37
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled
BMP Support => enabled
TGA Read Support => enabled
```
=> Add JPEG support to GD

dev-tools/scripts/user-container-setup.sh
On some images like `wordpress` or `dev-tools` there is no `/www/data` folder resulting in failure in backup user permissions script.
Testing this is a bit difficult as it is hard to trigger the scenario where the base lando user logic fails (your user id needs to be quite high is one way of doing it).
What I have done is changed the script condition to something like `[ 1 == 1 ] `, following the README configure one of my dev-envs to use local build for devtools instead of image and dropped volumes before every test using `destroy`.
=> Make chowning folder optional

dev-tools/setup.sh
The error for `wp option get siteurl` is different between a single and multisite.
Single: Error: The site you have requested is not installed.
https://github.com/wp-cli/wp-cli/blob/0b22dee2eabcfc9f9f84671003900155b0722543/php/utils-wp.php#L35
Multisite: Error: Site ‘969.vipdev.lndo.site/’ not found. Verify DOMAIN_CURRENT_SITE matches an existing site or use `--url=<url>` to override.
This change handles both variants.
=> patch multisite not installed check

.github/workflows/wp-test-base.yml, wp-test-base/Dockerfile
This PR adds a `wp-test-base` image. The image contains things common to our test runner images.
Its main advantage is the reduced build time. Because our runner images ship `nightly` releases of WordPress, they have to be rebuilt at least daily. However, PHP, Node.js, PHPUnit, etc do not have to be updated that often. By extracting the common dependencies into a separate image, we will reduce the time needed to build our test runners.
=> Add wp-test-base image

mariadb-lite/Dockerfile
This PR switches the base image from `circleci/mariadb:10.3` to `mariadb:10.3` and applies CircleCI-specific changes because:
* CircleCI images are only built for the `amd64` architecture;
* the 10.3 branch does not seem to receive security updates.
As a bonus, this PR fixes 18 low and 72 medium security vulnerabilities.
We still have several unpatched vulnerabilities in MariaDB (no fix exists):
* [mariadb: Improper Control of Generation of Code](https://avd.aquasec.com/nvd/cve-2021-27928);
* [mariadb: Crash in set_var.cc via certain UPDATE queries with nested subqueries](https://avd.aquasec.com/nvd/cve-2021-46662);
* [mariadb: Crash caused by mishandling of a pushdown from a HAVING clause](https://avd.aquasec.com/nvd/cve-2021-46666);
* [mariadb: Integer overflow in sql_lex.cc integer …
=> Update mariadb-lite image

php-fpm-alt/Dockerfile.80
* Bump alpine from 3.15.4 to 3.16.0;
* Do not create symlinks for `php` and `pecl`.
=> Update base image for php-fpm-alt:8.0

.github/workflows/wordpress.yml, README.md, dev-tools/Dockerfile, mu-plugins/Dockerfile, skeleton/Dockerfile, wordpress/Dockerfile
Update `ghcr.io/automattic/vip-container-images/alpine` from 3.15.4 to 3.16.0
=> Bump ghcr.io/automattic/vip-container-images/alpine to 3.16.0

wp-core-test-runner/Dockerfile, wp-test-runner/Dockerfile
This is the second part of #238.
This PR changes the base image from `cimg/base:stable-20.04` to `ghcr.io/automattic/vip-container-images/wp-test-base:latest` to speed up builds.
=> Change base image for test runners to automattic/vip-container-images/wp-test-base

mariadb-lite/Dockerfile
This causes fatal errors:
```
2022-06-20  7:31:10 0 [ERROR] InnoDB: preallocating 50331648 bytes for file ./ib_logfile1 failed with error 28
2022-06-20  7:31:10 0 [ERROR] InnoDB: Cannot set log file ./ib_logfile1 size to 50331648 bytes
2022-06-20  7:31:10 0 [ERROR] InnoDB: Database creation was aborted with error Generic error. You may need to delete the ibdata1 file before trying to start up again.
2022-06-20  7:31:10 0 [ERROR] Plugin 'InnoDB' init function returned error.
2022-06-20  7:31:10 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
```
This PR removes problematic settings.
=> InnoDB wants too much shared memory

wordpress/versions.json
=> Removes the possibility of using WordPress 5.5 in dev-env

dev-tools/wp-config-defaults.php
To avoid potential Identity Crises when production data gets imported in dev env we should set this constant.
=> Set JETPACK_STAGING_MODE to true

wordpress/versions.json
This PR will effectively remove the possibility of using WordPress version 5.6 in the vip development environment.
=> Remove WordPress version 5.6 from available versions

traefik/Dockerfile
2.7.x branch is no longer supported, we need to update.
@pschoffer I may need your help testing this.
=> Bump traefik to 2.8

statsd/Dockerfile
This affects the `statsd` image.
=> Update node:gallium-bullseye-slim's hash

.github/workflows/skeleton.yml
We need to be able to rebuild the container when Automattic/vip-go-skeleton repo changes.
For example, we had Automattic/vip-go-skeleton#89 but the image is still old.
=> [skeleton] Add workflow_dispatch trigger

mu-plugins/Dockerfile, mu-plugins/autoupdate.sh, mu-plugins/run.sh
We are working towards moving versioned Jetpack folders outside of mu-plugins into this mu-plugins-ext repo.
That way we can automate updates of those dependencies and combine them during deployment.
=> Support mu-plugins-ext in mu-plugins image

.github/workflows/stale.yml
This pull request introduces a GitHub action that runs daily and will automatically mark inactive issues and PRs as stale. Keeping issues and pull requests manageable and actionable is important for a codebase's health.
The default behavior of this action will mark issues and pull requests as stale after **60 days** of inactivity, by adding a label of `[Status] Stale` and leaving an explanatory comment ([example](https://github.com/Automattic/eslint-config-wpvip/issues/6#issuecomment-1215909749)). If another **7 days** of inactivity pass, it will be labeled `[Status] Autoclosed` and closed. (It can always be reopened, which resets the clock.)
This action ignores issues and PRs with the following labels:
- `[Pri] Critical`
- `[Status] Keep`
- `dependencies` (ensures that **Dependabot** …
=> Add GitHub action to mark inactive issues and PRs as stale

wordpress/add-version.sh
This PR fixes the [SC3014](https://www.shellcheck.net/wiki/SC3014) "In POSIX sh, `==` in place of `=` is undefined" issue.
=> Fix shell scripts

php-fpm/Dockerfile.74, php-fpm/Dockerfile.80, php-fpm/Dockerfile.81
This PR adds `su-exec` (a very lightweight `sudo`) to PHP images so that we can run `wp` as `www-data` from `vip dev-env exec`.
When `wp` is run as `root`, this sometimes leads to very nice permission errors:
```
$ vip dev-env exec -- wp vip-search index --setup --skip-confirm
Adding post mapping...
Success: Mapping sent
Indexing posts...
Processed 2/2. Last Object ID: 1
Number of posts indexed: 2
Total time elapsed: 12.239
Success: Done!
Warning: error_log(/tmp/logstash.log): Failed to open stream: Permission denied in /wp/wp-content/mu-plugins/logstash/class-logger.php on line 541 [$ /usr/local/bin/wp --allow-root vip-search index --setup --skip-confirm] [wp-content/mu-plugins/logstash/class-logger.php:541 error_log(), wp-includes/class-wp-hook.php:307 …
```
=> Add su-exec to PHP images

.github/dependabot.yml
We dropped Renovate but did not add back Dependeabot. This PR fixes that.
=> Add back Dependabot

wp-core-test-runner/Dockerfile, wp-core-test-runner/install-wp-core.sh
We don't use those builds anyway. If we don't build it, this will reduce the size of the image, as well as its build time.
=> Do not build core test images for WP older than 5.9

.github/workflows/wp-core-test-runner.yml, .github/workflows/wp-test-base.yml
* Core test runner builder needs to run on schedule to catch up with WordPress updates;
* Base test runner builder needs to run on schedule to ensure that we have current package versions
=> Set schedule for test runners

.github/workflows/wp-core-test-runner.yml, wp-core-test-runner/Dockerfile
The `wp-core-test-runner` takes the most time to build. This PR makes the image more cache friendly, which helps avoid unnecessary rebuilds.
=> Make the wp-core-test-runner image cache-friendly

wordpress/versions.json
Short and sweet. All WordPress image back-ports should be brought to current.
=> All dev-env images to their current

.github/workflows/dev-tools.yml, dev-tools/setup.sh, dev-tools/wp-config-defaults.php
This change
* renames expected container name `vip-search` -> `elasticsearch`
* adds reload of default config on every new install for change to take an effect
* bumps dev-tools version in order to not break old environments
=> Rename vip-search -> elasticsearch

wordpress/versions.json
WordPress 6.1 RC2 is not available by any tag. This PR attempts to add it by using the commit hash of the 6.1 branch.
=> Add WordPress 6.1 RC to dev-env

dev-tools/scripts/user-container-setup.sh, dev-tools/setup.sh
This PR replaces several bashisms, namely:
* In POSIX sh, [[ ]] is undefined
* In POSIX sh, == in place of = is undefined
* [ .. ] can't match globs. Use a case statement
in dev-tools scripts. This makes the code more portable.
=> fix(dev-tools): Replace bashisms with portable code

php-fpm/Dockerfile.74, php-fpm/Dockerfile.80, php-fpm/Dockerfile.81, php-fpm/Dockerfile.82
This PR adds the `shadow` package to `php-fpm` images.
There main reason for doing this is that in the PHP container, we always seem to remap the `www-data` UID:
```
vip 14:40:06.INFO  ==> Making sure www-data id ('82') is correctly mapped to '1000'
vip 14:40:06.WARN  ==> User www-data is NOT correctly mapped. Will attempt to fix that.
vip 14:40:06.INFO  ==> Installing shadow to support wider uid range
vip 14:40:09.INFO  ==> Making sure group www-data exists
vip 14:40:09.WARN  ==> Group www-data doesn't exist. Will attempt to create it.
vip 14:40:09.INFO  ==> SUCCESS: group added
vip 14:40:09.INFO  ==> SUCCESS: user was added
vip 14:40:09.INFO  ==> Making www-data owner of /home/www-data
vip 14:40:09.INFO  ==> Making sure www-data id ('1000') is correctly mapped to '1000'
```
This means …
=> feat(php-fpm): Add `shadow` to php-fpm images

dev-tools/setup.sh
https://github.com/Automattic/vip-container-images/pull/339 seems to have broken setup script.
For site check error "Error: The site you have requested is not installed." this if will NOT pass:
```
if ! echo "$site_exist_check_output" | grep -Eq "(Site .* not found)|(The site you have requested is not installed)"; then
```
Dropping the `!` seems to have done the trick.
=> Fix setup script

wordpress/versions.json
This change will align the available WordPress images with that of the available versions on the VIP platform. It does this with the following changes:
* Updates WordPress 6.1 to the official release tagged version.
* Removes the image for WordPress 5.7.8
=> Update WordPress 6.1 to Official Release

.github/workflows/update-wp-versions.yml
Ref: https://github.com/Automattic/vip-container-images/actions/runs/3384286899/jobs/5633628321#step:4:24
```bash
$ LATEST=$(wget https://api.wordpress.org/core/version-check/1.7/ -q -O - | jq -r '[.offers[].version] | unique | map(select( . >= "6.0")) | .[]')
$ echo "latest=${LATEST}"
latest=6.0.3
6.1
$ echo latest=${LATEST}
latest=6.0.3 6.1
```
If we quote the expression, WP versions are separated with the new line character, which upsets the runner.
=> fix(gha): Fix the "Unable to process file command 'output' successfully" error

.github/workflows/build-mu-plugins.yml, mu-plugins/Dockerfile.exp, mu-plugins/entrypoint.sh
This PR reduces the size of the `mu-plugins` image by keeping only one copy of the files and dropping the automatic updater.
BREAKING CHANGES:
* mu-plugins are no longer automatically updated;
* mu-plugins are built from the `staging` branch instead of `develop`.
Because `repository_dispatch` triggers can be run only from the main branch, this PR does not replace the original `Dockerfile` and tags the resulting image with the `experimental` tag. This way, we ensure that our changes do not break the dev environment, and it is still possible to test them.
=> feat(mu-plugins)!: Reduce the size of the image

.github/workflows/update-wp-versions.yml, wordpress/versions.json
- Add 6.1.1 
- Workaround a bug in the CI workflow that listed version tags as  as 6.0 6.1 6.1 for 6.0, 6.1, 6.1.1)
```
Adding version: 6.0 at ref: 6.0.3
Cacheable: true
Locked: true
Prerelease: false
Adding version: 6.1 at ref: 6.1
Cacheable: true
Locked: true
Prerelease: false
Adding version: 6.1 at ref: 6.1.1
Cacheable: true
Locked: true
Prerelease: false
6.1 already exists in versions.json
```
I feel like there's still opportunity for improvement, but it's good enough for now :)
=> WordPress: Update 6.1 to 6.1.1 and sort the versions in CI

.github/workflows/build-skeleton.yml, skeleton/Dockerfile
This PR adds a workflow to trigger a build of the Skeleton image.
The use case for this is when someone modifies the [automattic/vip-go-skeleton](https://github.com/Automattic/vip-go-skeleton) repository, the build is not triggered; a manual intervention is required. This has bitten us in the past.
With this workflow, it will be possible to trigger the build when the `vip-go-skeleton` repository has been pushed to.
=> ci: Add a workflow to trigger Skeleton build

php-fpm/Dockerfile.74, php-fpm/Dockerfile.80, php-fpm/Dockerfile.81, php-fpm/Dockerfile.82, php-fpm/rootfs74/usr/local/bin/run.sh, php-fpm/rootfs80/usr/local/bin/run.sh, php-fpm/rootfs81/usr/local/bin/run.sh, php-fpm/rootfs82/usr/local/bin/run.sh
This PR‌ adds support for MailHog into PHP-FPM images.
The presence of MailHog is detected from the `LANDO_INFO` environment variable. If MailHog is detected, the startup script updates the `sendmail_path` to use the MailHog service.
=> feat(php-fpm): Add support for MailHog

dev-tools/wp-config-defaults.php
This PR removes statsd-related constants from wp-config-defaults.php.
=> fix(dev-tools): Remove all traces of statsd

wordpress/extra/wp-config.php
This PR adds the placement anchor to `wp-config.php` so that `wp config set` command works.
Without the anchor, it fails with
```
Error: Could not process the 'wp-config.php' transformation.
Reason: Unable to locate placement anchor.
```
=> fix(wordpress): Add placement anchor to wp-config.php

dev-tools/setup.sh
This PR updates the setup script so that it activates ES features by defining `VIP_ENABLE_VIP_SEARCH` and `VIP_ENABLE_VIP_SEARCH_QUERY_INTEGRATION` to `true` when
1. The dev env has the ElasticSearch enabled
2. The dev env sources the application code from an image
This saves the user a couple of calls to `vip dev-env exec -- wp config set ...` and `vip dev-env exec -- wp vip-search index --setup`.
⚠️ #391 needs ti be merged and built first, because it contains an import bugfix this PR relies upon.
=> feat(dev-tools): Automatically activate ES when dev-env has elasticsearch and uses the demo app code image

dev-tools/setup.sh
Until https://github.com/Automattic/vip-cli/pull/1229 is deployed, we have to check whether ES is already online before trying to contact it. Otherwise, post mapping might fail.
Ref: https://github.com/Automattic/vip-go-mu-plugins/actions/runs/3849360436/jobs/6558708351#step:13:225
=> fix(dev-tools): Wait for ES to come online before trying to contact it

.github/workflows/traefik.yml
So that we don't have to update Lando every time there is new release of traefik.
=> ci(traefic_openssl): Tag the image as `latest`

dev-tools/setup.sh
This PR adds a check whether `LANDO_INFO` is set before messing up with Elasticsearch. This will allow us to use this image in a Landoless environment, such as DevContainers.
=> fix(dev-scripts): Check whether LANDO_INFO is set

dev-tools/setup.sh
Use `wait_for_status` and `timeout` instead of a loop. Also, accept `yellow` status as OK.
=> refactor(dev-tools): Improve ES health check

mu-plugins/Dockerfile, nginx/Dockerfile, wordpress/Dockerfile
This PR adds `shadow` package to `wordpress`, `nginx`, and `mu-plugins`.
Specifically, we will need `usermod` and `groupmod` to update UID/GID in Landoless environments.
=> feat: Add shadow package

php-fpm/rootfs74/usr/local/bin/run.sh, php-fpm/rootfs80/usr/local/bin/run.sh, php-fpm/rootfs81/usr/local/bin/run.sh, php-fpm/rootfs82/usr/local/bin/run.sh
Currently, the startiup script relies upon the `LANDO_INFO` environment variable to find out whether MailHog is enabled.
This PR adds another var, `ENABLE_MAILHOG`, to allow this container to be used in Landoless environments like Codespaces.
=> feat(php-fpm): Add env var to enable MailHog

dev-tools/setup.sh
Currently, `setup.sh` relies upon the `LANDO_INFO` environment variable to find out whether ES is enabled.
This PR adds another var, `ENABLE_ELASTICSEARCH`, to allow this container to be used in Landoless environments like Codespaces.
=> feat(dev-tools): Add env var to enable ES

dev-tools/setup.sh
This PR adds a code to wait for `mu-plugins` become ready to avoid some unpleasant races.
=> fix(dev-env): Add code to wait for mu-plugins to become ready

php-fpm/Dockerfile.74, php-fpm/Dockerfile.80, php-fpm/Dockerfile.81, php-fpm/Dockerfile.82, php-fpm/rootfs-common/etc/vip-motd, php-fpm/rootfs-common/home/www-data/.bashrc, php-fpm/rootfs-common/root/.bashrc
Previously when logging onto container we saw the default `bash-5.1# ` prompt. Now we'll display a banner and modify the prompt to be more descriptive - it'll show the user and the current working directory. 
We added a new folder rootfs-common, that will contain anything that needs to be shared across different image version.
=> Add welcome banner and improve terminal prompt for PHP-FPM containers

dev-tools/setup.sh
> In MySQL 8.0, you must create a user first before assigning permission, as the GRANT command will no longer create a new user.
=> fix(dev-tools): Support MySQL 8 syntax for creating users

dev-tools/dev-env-plugin.php
This PR updates `$_SERVER['HTTP_HOST']` to match the real hostname of the codespace.
=> fix(dev-tools): Fix Host header for Codespaces

dev-tools/setup.sh
Ref: https://github.com/Automattic/vip-go-mu-plugins/actions/runs/4294727373/jobs/7485334888
=> fix(dev-tools): Check for `.version` only if `mu-plugins` is a mount point

dev-tools/wp-config-defaults.php
GitHub no longer exposes `$_SERVER['CODESPACES']`, so we have to go another way.
=> fix(dev-tools): Fix detection of GitHub Codespaces

dev-tools/setup.sh
Related: https://github.com/Automattic/vip-go-mu-plugins/pull/4247
Do not load themes for `wp core install` to ensure that user code does not interfere with the process.
=> fix: Skip themes on WP install

dev-tools/dev-env-plugin.php
This adds support for dev-env to autologin with clicking a link (One-click login).
The CLI counterpart to this is - https://github.com/Automattic/vip-cli/pull/1317
The only requirement is to have `vip-dev-autologin` as query parameter.
The next step is to include this link to the info table on environment startup:
http://vip-local.vipdev.lndo.site/wp-admin/?vip-dev-autologin
This will login users directly.
Props to @rinatkhaziev for inspiration
**EDIT**
After few iterations we decided to step up the security around this change. Now there is a unique unlock key which is generated on dev-env creation/update and injected as an environment variable. At the same time this key is shown to users in cli when starting the environment.
=> Adds autologin support

php-fpm/rootfs74/etc/php7/conf.d/xdebug.ini.template, php-fpm/rootfs80/etc/php8/conf.d/xdebug.ini.template, php-fpm/rootfs81/etc/php81/conf.d/xdebug.ini.template, php-fpm/rootfs82/etc/php82/conf.d/xdebug.ini.template
To cover more scenarios and support xdebug with zero config we are adding discover_client_host.
That way xdebug will also atempt to connect to the caller as well as backup to client_host (`host.docker.internal`)
Change your dev-env .lando.yml to something like:
```
php:
type: compose
services:
build:
context: /home/pavel/git/automattic/vip-container-images/php-fpm
dockerfile: /home/pavel/git/automattic/vip-container-images/php-fpm/Dockerfile.80
```
=> Add xdebug config - discover_client_host

wordpress/.dockerignore, wordpress/Dockerfile, wordpress/entrypoint.sh
This PR is required for https://github.com/Automattic/vip-cli/pull/1341 so that we can make `wordpress` an init-only container.
=> feat(wordpress): Add entrypoint script

dev-tools/dev-env-plugin.php
If user is already logged in the wp-admin stays with : `?vip-dev-autologin=f474326f-ec59-46b9-b272-6c4f836e9c59`
This change adds one more redirect in that case in order to shave off the param
=> Autologin: drop param if logged in already

dev-tools/dev-env-plugin.php, dev-tools/wp-config-defaults.php
This change prints php errors to stderr. This in turn makes it readable from `docker logs` which is what is used under the hood of `vip dev-env logs`.
We moved the setting to both mu-plugin and wp-config so that we catch logs both before and after mu-plugins. 
We also added OS check.
=> Include php errors to stderr

php-fpm-ubuntu/rootfs/etc/default/locale, php-fpm/Dockerfile.74, php-fpm/Dockerfile.80, php-fpm/Dockerfile.81, php-fpm/Dockerfile.82, php-fpm/rootfs/etc/default/locale, php-fpm/rootfs/usr/local/bin/run.sh, php-fpm/rootfs/usr/local/bin/wp-cron.sh
Steps to test:
1. `vip dev-env create < /dev/null`
2. `vip dev-env update -P image:ghcr.io/automattic/vip-container-images/php-fpm-ubuntu:8.0`
3. `vip dev-env start`
4. Build PHP 8 locally: `docker build -t ghcr.io/automattic/vip-container-images/php-fpm-ubuntu:8.0 -f Dockerfile.80 .`
5. Add `ENABLE_CRON: 1` after `XDEBUG: disable` to `.lando.yml`
6. `vip dev-env start`
7. `crontab -l` should show `*/10 * * * * /usr/local/bin/wp core is-installed && /usr/bin/flock -n /tmp/wp-cron.lock /usr/local/bin/wp cron event run --due-now`
8. `ps faux | grep cron` should show `cron` is running
9. Run `wp cron event list`, then meditate for 10 minutes, run `wp cron event list` again. `next_run_gmt` should change for `a8c_cron_control_force_publish_missed_schedules` and `vip_config_sync_cron`.
=> feat(php-fpm): Add support for running cron

php-fpm/rootfs/usr/local/bin/run.sh
This fixes
```
php_1             | 2023-06-20T05:55:52.041279178Z cp: cannot stat '': No such file or directory
```
when XDebug is enabled.
=> fix(php-fpm): Remove erroneous `cp` command

dev-tools/wp-config-defaults.php
We load vip-config.php currently from `/wp/wp-content/vip-config/vip-config.php` however in live environments the vip-config folders is mapped directly to `/wp/vip-config`  (not under `wp-content`).
We should migrate the location to more closely match the prod environment. That way we can support other files too such as `client-sunrise.php` which [is loaded ](https://github.com/Automattic/vip-go-mu-plugins/blob/7294c3902d473c57c58e8505d4ad396de3470d0b/lib/sunrise/sunrise.php#L100-L106)from  `/wp/vip-config/client-sunrise.php`
This is first part of the change where we load from both places. After that we cna change the mapping to the new place
=> Load from vip-config too

dev-tools/wp-config-defaults.php
The final piece of VIP File Service shim/"mimicking" are the filters that strip intermediate sizes and allow passing dynamic arguments.
This also explicitly disables Stream Wrapper functionality as it won't ever work in Local Dev Env.
=> Define FILES_ACCESS_TOKEN to enable Photon/Files Service resizing, explicitly disable stream wrapper

dev-tools/dev-env-plugin.php
Running into `Undefined constant "VIP_GO_APP_ENVIRONMENT" in /var/www/html/wp-content/mu-plugins/dev-env-plugin.php:103` as I try to do `npm run search-env:start` for tests.
=> Fix " Undefined constant "VIP_GO_APP_ENVIRONMENT"

php-fpm/Dockerfile.83
Now that https://github.com/oerdnj/deb.sury.org/issues/2025 has been fixed, it is time to undo our fix.
Related: #536, #537
=> refactor(php-fpm): undo hack for php 8.3

php-fpm/Dockerfile.74, php-fpm/Dockerfile.80, php-fpm/Dockerfile.81, php-fpm/Dockerfile.82, php-fpm/Dockerfile.83
This PR fixes the docker:S6587 issue: Cache should be cleaned after package installation
> Docker images should only contain necessary data. The package index is optional for the correct working of the installed software. Storing an index also increases the size of the Docker image. It should be reduced to speed up deployments and reduce storage and bandwidth.
=> fix(php-fpm): clean cache after package installation

.github/workflows/alpine.yml, .github/workflows/dev-tools.yml, .github/workflows/mu-plugins.yml, .github/workflows/nginx.yml, .github/workflows/skeleton.yml, .github/workflows/traefik.yml, nginx/Dockerfile
This PR:
* allows for building Docker images from the directory where `Dockerfile` is located, not from the repo's root directory;
* reduces the amount of data sent to the Docker daemon to build the image.
=> ci: allow for building images from Dockerfile directory

.github/actions/build-docker-image/action.yml, .github/actions/build-docker-image/markdown.tpl, .github/workflows/alpine.yml, .github/workflows/dev-tools.yml, .github/workflows/mu-plugins.yml, .github/workflows/nginx.yml, .github/workflows/photon.yml, .github/workflows/php-fpm.yml, .github/workflows/skeleton.yml, .github/workflows/traefik.yml, .github/workflows/wordpress.yml
* Refactor CI workflows to avoid unnecessary code duplication
* Add security scan (#239)
* Fix bugs (#563)
Supersedes: #563
Supersedes: #239
=> ci: refactor build workflows

.github/workflows/alpine.yml, alpine/Dockerfile
Fix CVE-2023-5363 (medium severity) affecting `libssl3` and `libcrypto3`.
Ref: https://github.com/Automattic/vip-container-images/pull/565#issuecomment-1784572462
Ref: https://avd.aquasec.com/nvd/cve-2023-5363
=> security(alpine): fix CVE-2023-5363

.github/workflows/dev-tools.yml, .github/workflows/nginx.yml, .github/workflows/photon.yml, .github/workflows/php-fpm.yml, .github/workflows/traefik.yml
This PR adds a `workflow_dispatch` trigger to all our build workflows so that we can trigger them manually in case we need to rebuild an image.
Note: Alpine workflow is updated in #568 in order not to create merge conflicts.
=> ci: add workflow_dispatch to all build workflows

nginx/Dockerfile
- CVE-2023-43785 (medium severity): out-of-bounds memory access in _XkbReadKeySyms()
- CVE-2023-43786 (medium severity): stack exhaustion from infinite recursion in PutSubImage()
- CVE-2023-43787 (high severity): integer overflow in XCreateImage() leading to a heap overflow
=> security(nginx): fix CVE-2023-43785, CVE-2023-43786, CVE-2023-43787

dev-tools/Dockerfile, mu-plugins/Dockerfile, skeleton/Dockerfile, wordpress/Dockerfile
Affects:
* dev-tools
* mu-plugins
* skeleton
* wordpress
=> security: fix CVE-2023-5678

mu-plugins/Dockerfile
This shaves off about 100mb from the image.
=> mu-plugins: .dockerignore was not taking any effect, switching to rsync approach we do for mu-plugins-ext, also uninstall git

mu-plugins/Dockerfile
To prevent bloat from integrations making it to the dev env we've introduced a new .devenvignore file where we can block particular versions from the build process.
=> Add .devenvignore support for ext repo

dev-tools/setup.sh
This fixes [SC3037](https://www.shellcheck.net/wiki/SC3037): In POSIX sh, echo flags are undefined.
=> fix(dev-env): use printf instead of echo for waiting messages

dev-tools/setup.sh
=> fix(dev-tools): grant `SET_ANY_DEFINER` privilege to `wordpress` user

dev-tools/setup.sh
The issue was that `docker-compose.yml` instructed MySQL to create the user: https://github.com/Automattic/vip-cli/blob/trunk/assets/dev-env.lando.template.yml.ejs#L99-L101
As a consequence, `if ! mysql -h "$db_host" -u wordpress -pwordpress wordpress -e "SELECT 'testing_db'" >/dev/null 2>&1; then` was always false, and we did not grant the user the `SET_ANY_DEFINER` privilege.
Moreover, the `GRANT ALL ON *.* TO 'netapp'@'%';` caused issues later because MySQL grants all privileges to the user [only on the specific database](https://hub.docker.com/_/mysql). We grant `netapp` all privileges on all databases, and MySQL was unhappy about it on import: "Access denied; you need (at least one of) the SYSTEM_USER privilege(s) for this operation".
What has changed now:
* We do not try to create …
=> fix(dev-tools): grant privileges to MySQL users properly

wordpress/versions.json
Pointed at the "branch 6.5" commit in this branch: https://github.com/WordPress/WordPress/commits/6.5-branch
=> Update to WP 6.5 RC1

nginx/default.conf
Sometimes customers get 502 errors which are tricky to debug, this should give a bit of a breathing room.
Probably worth doing a custom 502 error page to describe potential solutions for 502 errors.
=> Bump up fastcgi_buffer_size to 64k to pad prod value a bit

.github/actions/build-docker-image/action.yml, .github/workflows/alpine.yml, .github/workflows/build-skeleton.yml, .github/workflows/dev-tools.yml, .github/workflows/mu-plugins.yml, .github/workflows/nginx.yml, .github/workflows/photon.yml, .github/workflows/php-fpm.yml, .github/workflows/skeleton.yml, .github/workflows/traefik.yml, .github/workflows/wordpress.yml
Artifact attestations enable us to create unfalsifiable provenance and integrity guarantees for the images we build, thus increasing their supply chain security. People who consume our images can verify where and how they were built.
=> ci: attest build provenance for Docker images

.github/actions/build-docker-image/action.yml
Now that the provenance attestations are [successfully generated and pass validation](https://github.com/Automattic/vip-container-images/attestations), it is time to push them into the container registry.
=> ci: publish attestations to the container registry

php-fpm/Dockerfile.81, php-fpm/Dockerfile.82, php-fpm/Dockerfile.83
`eatmydata` in Ubuntu is a bit broken: it sets the `LD_LIBRARY_PATH` environment variable to `/usr/lib/libeatmydata`:
```sh
LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+"$LD_LIBRARY_PATH:"}/usr/lib/libeatmydata
LD_PRELOAD=${LD_PRELOAD:+"$LD_PRELOAD "}libeatmydata.so
export LD_LIBRARY_PATH LD_PRELOAD
```
However, `libeatmydata.so` is located in a platform-dependent location, `/usr/lib/$(uname -m)-linux-gnu`.
This PR creates the `/usr/lib/libeatmydata` directory and symlinks all files matching `/usr/lib/$(uname -m)-linux-gnu/libeatmydata.so*` into it.
=> fix(php-fpm): honor `LD_LIBRARY_PATH` `eatmydata` expects

wp-test-runner/Dockerfile
`eatmydata` in Ubuntu is a bit broken: it sets the `LD_LIBRARY_PATH` environment variable to `/usr/lib/libeatmydata`:
```sh
LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+"$LD_LIBRARY_PATH:"}/usr/lib/libeatmydata
LD_PRELOAD=${LD_PRELOAD:+"$LD_PRELOAD "}libeatmydata.so
export LD_LIBRARY_PATH LD_PRELOAD
```
However, `libeatmydata.so` is located in a platform-dependent location, `/usr/lib/$(uname -m)-linux-gnu`.
This PR creates the `/usr/lib/libeatmydata` directory and symlinks all files matching `/usr/lib/$(uname -m)-linux-gnu/libeatmydata.so*` into it.
Furthermore, this allows us not to use the platform-specific `LD_PRELOAD‌` path and refer to `/usr/lib/libeatmydata/libeatmydata.so` instead.
=> fix(wp-test-runner): correct library path in `LD_PRELOAD`

nginx/default.conf
Some prefer debugging PHP runtime errors in browser so the previous change in #682 negatively affected that workflow.
=> Remove 500 from http status that gets intercepted by a custom error page

php-fpm/Dockerfile.83
```
loadkeys 07:09:38.89 INFO  ==> Scanning /lando/keys for keys...
loadkeys 07:09:38.89 INFO  ==> Scanning /var/www/.ssh for keys...
loadkeys 07:09:38.89 INFO  ==> Scanning /user/.ssh for keys...
loadkeys 07:09:38.90 INFO  ==> Found keys 
loadkeys 07:09:38.90 INFO  ==> Using the following keys: 
vip 07:09:38.90 INFO  ==> Making sure www-data id ('33') is correctly mapped to '1000'
vip 07:09:38.90 WARN  ==> User www-data is NOT correctly mapped. Will attempt to fix that.
vip 07:09:39.17 INFO  ==> Making sure group www-data exists
vip 07:09:39.17 WARN  ==> Group www-data doesn't exist. Will attempt to create it.
vip 07:09:39.22 INFO  ==> SUCCESS: group added
useradd: UID 1000 is not unique
vip 07:09:39.29 ERROR ==> User was not added
lando 07:09:39.29 INFO  ==> Lando handing off to: run.sh …
```
=> fix(php-fpm): startup issues for php-fpm 8.3

dev-tools/wp-config.php.tpl
This change allows for `WP_DEBUG`, `WP_DEBUG_LOG`, and `WP_DEBUG_DISPLAY` to be set in `vip-config.php` by requiring `wp-config-defaults.php` before setting those constants in `wp-config.php.tpl`.
=> Allow setting WP_DEBUG, WP_DEBUG_LOG, and WP_DEBUG_DISPLAY in vip-config.php

php-fpm/Dockerfile.81, php-fpm/Dockerfile.82, php-fpm/Dockerfile.83, wordpress/versions.json
Gonna need mydumper support on vip-cli so here's what the code is for.
Currently testing it.
Steps assumes you have an environment created from `vip dev-env create`.
Also, I suggest running `vip dev-env` from your **sandbox**. Since we now have 70 GB on our sandbox, we can finally test these stuff there. The machine on your sandbox has way faster internet and likely to have even more cores, too.
1. Make sure your dev-env is down i.e. `vip dev-env stop --slug your-slug`
2. [Follow the readme](https://github.com/Automattic/vip-container-images#using-image-locally-in-dev-env) but apply the steps to the `php:` service in the `.yml` file.
3. Run `vip dev-env start --slug your-slug`
4. It should run without any errors
5. Then, execute `vip dev-env shell --slug your-slug`
6. Then, run `mydumper …
=> Add mydumper

php-fpm/Dockerfile.81, php-fpm/Dockerfile.82, php-fpm/Dockerfile.83
This PR addresses the warning
> ** (myloader:1737): WARNING **: 18:09:31.767: zstd command not found on any static location, use --exec-per-thread for non default locations
Ref: 191146-z
=> feat(php-fpm): add `ztsd` to the image

.github/actions/build-docker-image/action.yml
0.48.3 started to fail with:
```
2024-09-30T08:53:00.206Z	FATAL	init error: DB error: failed to download vulnerability DB: database download error: OCI repository error: 1 error occurred:
* GET https://ghcr.io/v2/aquasecurity/trivy-db/manifests/2: TOOMANYREQUESTS: retry-after: 337.839µs, allowed: 44000/minute
```
Let's see if the latest version helps.
=> ci: use the latest version of Trivy for security scans

mu-plugins/Dockerfile
In this PR, we modify the build process to use the staging image matching the build platform architecture. This is OK because we stage only platform-independent files.
This will make things slightly faster because the system will not have to use emulation for `git clone` and `rsync`.
=> build(mu-plugins): use native platform image to prepare mu-plugins

wordpress/Dockerfile
Same as #909 but for WordPress.
=> build(wordpress): use native platform image for staging build

.github/workflows/traefik.yml, traefik/Dockerfile, traefik/Dockerfile.v2, traefik/Dockerfile.v3
Build both Traefik v2 and v3.
* Because we tagged the original `traefik` image as `latest`, we cannot just build v3 and call it `latest` because this will break old versions of VIP CLI (for Lando, there are incompatible changes in v3);
* The proposed solution is to keep `v2` as latest and tag `v3` as `v3`. Old versions of VIP CLI will continue to use the `latest` tag, while newer versions will use `v3`.
=> feat(traefik): build both v2 and v3

.github/actions/build-docker-image/action.yml
Whenever we rebuild an image (without a cache), its digest changes. If we push that image into a repository, this will cause rebuilds of dependent images.
Ref: https://docs.docker.com/build/ci/github-actions/reproducible-builds/
=> feat: reproducible builds

.github/actions/build-docker-image/action.yml
We pass the wrong socket to Trivy. The `crazy-max/ghaction-setup-docker` action creates its own context with a different socket. We get incorrect results because we pass `/var/run/docker.sock`.
=> fix: determine the correct Docker socket from the context

mu-plugins/run.sh
Allow the entrypoint script to terminate to free up some resources.
The `vip-mu-plugins` service is [marked as `initOnly`](https://github.com/Automattic/vip-cli/blob/trunk/assets/dev-env.lando.template.yml.ejs#L210); therefore, this change is safe.
Related: Automattic/vip-cli#1341
Also, remove the `chown` logic because the image does not have the `www-data` user, and the condition is always false.
=> refactor(mu-plugins): let entrypoint script terminate

skeleton/Dockerfile
This PR switches the base image for `skeleton` from `alpine` to `busybox`. This reduces the image size (22.5MB vs 32.9MB) and update frequency (the `busybox` binary is the only executable component of the image; it is updated less frequently and has much fewer vulnerabilities than a full-fledged image).
Also, because the `ADD` command can [add files from a Git repository](https://docs.docker.com/reference/dockerfile/#adding-files-from-a-git-repository), we simplify the build process by not using `git`. The build process will be faster because Docker does not need to execute anything in the foreign (emulated) architecture.
Unlike #984, this PR does not require changes to VIP CLI.
=> refactor(skeleton): switch to `busybox` and simplify build

.github/actions/build-docker-image/action.yml, .github/workflows/dev-tools.yml, .github/workflows/helpers.yml, .github/workflows/skeleton.yml
This PR adds an option to disable the security scan of the target image. This makes sense for images based on `scratch` or `busybox` because Trivy is unable to find out versions of the packages used or the OS distro (because there isn't any).
This will reduce the noise and make some builds run faster.
=> ci: add an option to disable image scan

.github/actions/build-docker-image/action.yml
See https://github.com/docker/setup-docker-action/releases/tag/v4.0.0
> Repo moved to [docker/setup-docker-action](https://github.com/docker/setup-docker-action)
=> ci: rename `crazy-max/ghaction-setup-docker` to `docker/setup-docker-action`

dev-tools/Dockerfile
1. Copy dev-tools to both `/dev-tools-orig` and `/dev-tools` (the latter destination is required for backward compatibility).
2. When the container starts, sync tools from `/dev-tools-orig` to `/dev-tools`.
This will simplify the logic in VIP CLI (it will not have to find and remove devtools volume every time the environment starts) and ensure that the volume has the latest tools.
VIP CLI PR: Automattic/vip-cli#2139
Update:
3. Switch the base image from `alpine` to `busybox` and add a static build of `rsync`. This reduces the image size from 11.8MB to 3.05MB and eliminates the need to update the image weekly (`busybox` updates less often and has fewer security vulnerabilities than a full-fledged distro).
4. Make the build process more cache-friendly by [making copied files independent on …
=> refactor(dev-tools): always update `/devtools`

dev-tools/dev-env-plugin.php
This PR disables Jetpack's Web Application Firewall in local development environments.
Fixes: Automattic/vip-go-mu-plugins#6001
=> fix: disable Jetpack WAF

.github/workflows/wordpress.yml, wordpress/Dockerfile
This PR migrates WordPress images to `busybox`, resulting in smaller images and less frequent updates.
=> refactor(wordpress): migrate to busybox

.github/actions/build-docker-image/action.yml
This PR updates the `build-docker-image` action to ensure that the image name is always present in the comment, even if Trivy reports no data. This will allow the `peter-evans/find-comment` action to locate the comment.
=> ci: update `build-docker-image` action to include comment marker

mu-plugins/Dockerfile
This PR migrates `mu-plugins` to `busybox`. This results in a smaller image size and less frequent updates.
=> refactor(mu-plugins): migrate to `busybox`

helpers/Dockerfile
Ref: https://github.com/Cyan4973/xxHash/releases/tag/v0.8.3
=> chore: update `xxHash` to 0.8.3

helpers/Dockerfile
Ref: https://github.com/RsyncProject/rsync/releases/tag/v3.4.0
Ref: https://github.com/RsyncProject/rsync/releases/tag/v3.4.1
CVEs addressed: CVE-2024-12084, CVE-2024-12085, CVE-2024-12086, CVE-2024-12087, CVE-2024-12088, CVE-2024-12747
Use-after-free: RsyncProject/rsync#706
=> fix(helpers): update `rsync` to 3.4.1to fix several CVEs

wordpress/dev-tools/dev-env-plugin.php
`null` resulted in printing of JSON. as a result of `require $config_path`
=> Integrations config: fallback to empty array when $slug for the integrations is missing from integrations.json

.github/workflows/update-wp-versions.yml
6.1 was removed from the platform, we need to match it here.
=> Bump minimum to 6.2 in version checker

wordpress/dev-tools/wp-config-multisite.php.tpl
Set `SUNRISE` to `true` for multisite installations.
See BB8-12188 and [Configuration for local development](https://docs.wpvip.com/wordpress-on-vip/multisites/sunrise-php/#h-configuration-for-local-development).
=> fix(wordpress): set `SUNRISE` for multisite

traefik/Dockerfile.v3
This addresses CVE-2024-13176.
=> chore: update traefik v3 to 3.3.3

wordpress/Dockerfile
This PR removes the WordPress Tests Library from the WordPress image. We are introducing another dedicated image with WPTL (#1086).
This approach will save some space and bandwidth for the users who don't need WPTL.
The PR effectively reverts #1074.
=> refactor(wordpress): remove WPTL from WordPress image

wordpress/Dockerfile
Reverts Automattic/vip-container-images#1087
It turns out that it is impossible to introduce new services in `.lando.local.yml` 😢
=> Revert "refactor(wordpress): remove WPTL from WordPress image"

.github/actions/build-docker-image/action.yml
* Bump `actions/cache` from 4.2.1 to 4.2.2 (#1094)
* Bump `actions/attest-build-provenance` from 2.2.0 to 2.2.2 (#1093)
* Bump `docker/setup-docker-action` from 4.1.0 to 4.2.0 (#1092)
=> build: update actions

wordpress/dev-tools/setup.sh
Turn environment variables like `VIP_ENV_VAR_xxx` into PHP constants for compatibility with `vip_get_env_var()`.
=> feat(wordpress): add support for environment variables

wordpress/dev-tools/setup.sh
If the constant corresponding to the environment variable does not exist in `wp-config.php`, the dev environment fails to start.
Related: PLTFRM-590
=> fix(wordpress): env var processing

photon/Dockerfile
Fix the `Uncaught Error: Class "Photon_OpenCV" not found` error.
Ref: PLTFRM-741
=> fix(photon): stick to `r645` to use `gmagick`

wordpress/dev-tools/setup.sh
Adds optional parameter of `--wp-admin_password <password>` in `setup.sh`. If none passed in, defaults to `password`.
=> Dev-tools/setup.sh: Add `--wpadmin_password` parameter

alpine/Dockerfile, photon/Dockerfile
This pull request updates the base Alpine image version across multiple Dockerfiles to ensure the use of the latest patch release for improved security and stability.
* Updated the base image in `alpine/Dockerfile` from `alpine:3.22.0` to `alpine:3.22.1` to incorporate the latest updates and security fixes.
* Updated the base image in `photon/Dockerfile` for both build and runtime stages from `alpine:3.22.0` to `alpine:3.22.1`, ensuring consistency and leveraging the latest Alpine improvements. [[1]](diffhunk://#diff-4df650c90586f78b0769e6a54876a4b0d037f00eaef773ca3ffa2eb896aa3d4dL1-R1) [[2]](diffhunk://#diff-4df650c90586f78b0769e6a54876a4b0d037f00eaef773ca3ffa2eb896aa3d4dL10-R10)
=> chore(deps): update `alpine` base image to 3.22.1

wordpress/dev-tools/backfill-env-vars.php
Ref: https://docs.docker.com/reference/compose-file/services/#env_file-format
Ref: https://github.com/Automattic/vip-cli/pull/2398
=> fix(wordpress): handle common escape sequences in environment variables

wordpress/versions.json
This pull request updates the supported WordPress versions in the `wordpress/versions.json` file to reflect the latest patch releases and removes support for older minor versions.
WordPress version updates:
* Updated the `ref` values for versions `6.7`, `6.6`, `6.5`, and `6.4` to their latest patch releases: `6.7.4`, `6.6.4`, `6.5.7`, and `6.4.7` respectively.
Version deprecations:
* Removed support for older minor versions `6.3.6` and `6.2.7` from the list.
=> Update WordPress version references in JSON

php-helpers/Dockerfile
This pull request adds support for PHP 8.5 to the `php-helpers` Docker build process by introducing a new build stage and ensuring the `timezonedb` extension is included for this PHP version.
Dockerfile updates for PHP 8.5 support:
* Added a new build stage named `php85` to the `php-helpers/Dockerfile` for building the `timezonedb` extension with PHP 8.5.
* Updated the final image to copy the `timezonedb.so` extension for PHP 8.5 from the new build stage into the appropriate directory.
=> fix(php-helpers): copy PHP 8.5 extensions to the final image
